# Generated by Django 6.0.5 on 2026-06-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date', '-end_date', 'institution']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date', '-end_date', 'company']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-proficiency', 'name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
